# Generated by Django 4.2 on 2023-04-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category_item_description_item_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
