# Generated by Django 4.2 on 2023-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_orderitem_ordered_remove_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirts'), ('SW', 'Sports wear'), ('OW', 'Outwear')], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='xad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='dfd', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='lable',
            field=models.CharField(choices=[('Y', 'primary'), ('W', 'secondary'), ('D', 'danger')], default='dfdyf', max_length=1),
            preserve_default=False,
        ),
    ]
